for i_hat = 1:pm.num
    
    if a==0
        % a==0: coarse grid.
        
        MTX_K.fre.OR.iter.hat =  MTX_K.fre.OR.I11_I20_IS0*pm.pre.val.rect(i_hat, 1)+...
            MTX_K.fre.OR.I10_I21_IS0*pm.pre.val.rect(i_hat, 2)+...
            MTX_K.fre.OR.I10_I20_IS1*0.01;
        
        MTX.hat.ori = MTX_K.fre.OR.iter.hat+a1*MTX_C.fre.OR.trial.loop+a2*MTX_M.fre.OR.all;
        
        MTX.hat.inv = inv(MTX.hat.ori);
        
        MTX.hat.ori_asmbl.rect((i_hat*length(MTX.hat.ori)-length(MTX.hat.ori)+1):i_hat*length(MTX.hat.ori), :)...
            = MTX.hat.ori_asmbl.rect((i_hat*length(MTX.hat.ori)-length(MTX.hat.ori)+1):i_hat*length(MTX.hat.ori), :)...
            +MTX.hat.inv;
        
    elseif a==1
        % a==1: refined grid.
        MTX_K.fre.OR.iter.hat.lu =  MTX_K.fre.OR.I11_I20_IS0*pm.pre.lu(i_hat, 3)+...
            MTX_K.fre.OR.I10_I21_IS0*pm.pre.lu(i_hat, 4)+...
            MTX_K.fre.OR.I10_I20_IS1*0.01;
        MTX.hat.ori.lu = MTX_K.fre.OR.iter.hat.lu+a1*MTX_C.fre.OR.trial.loop+a2*MTX_M.fre.OR.all;
        MTX.hat.inv.lu = inv(MTX.hat.ori.lu);
        MTX.hat.ori_asmbl.lu((i_hat*length(MTX.hat.ori.lu)-length(MTX.hat.ori.lu)+1):i_hat*length(MTX.hat.ori.lu), :)...
            = MTX.hat.ori_asmbl.lu((i_hat*length(MTX.hat.ori.lu)-length(MTX.hat.ori.lu)+1):i_hat*length(MTX.hat.ori.lu), :)...
            +MTX.hat.inv.lu;
        
        MTX_K.fre.OR.iter.hat.ru =  MTX_K.fre.OR.I11_I20_IS0*pm.pre.ru(i_hat, 3)+...
            MTX_K.fre.OR.I10_I21_IS0*pm.pre.ru(i_hat, 4)+...
            MTX_K.fre.OR.I10_I20_IS1*0.01;
        MTX.hat.ori.ru = MTX_K.fre.OR.iter.hat.ru+a1*MTX_C.fre.OR.trial.loop+a2*MTX_M.fre.OR.all;
        MTX.hat.inv.ru = inv(MTX.hat.ori.ru);
        MTX.hat.ori_asmbl.ru((i_hat*length(MTX.hat.ori.ru)-length(MTX.hat.ori.ru)+1):i_hat*length(MTX.hat.ori.ru), :)...
            = MTX.hat.ori_asmbl.ru((i_hat*length(MTX.hat.ori.ru)-length(MTX.hat.ori.ru)+1):i_hat*length(MTX.hat.ori.ru), :)...
            +MTX.hat.inv.ru;
        
        MTX_K.fre.OR.iter.hat.ld =  MTX_K.fre.OR.I11_I20_IS0*pm.pre.ld(i_hat, 3)+...
            MTX_K.fre.OR.I10_I21_IS0*pm.pre.ld(i_hat, 4)+...
            MTX_K.fre.OR.I10_I20_IS1*0.01;
        MTX.hat.ori.ld = MTX_K.fre.OR.iter.hat.ld+a1*MTX_C.fre.OR.trial.loop+a2*MTX_M.fre.OR.all;
        MTX.hat.inv.ld = inv(MTX.hat.ori.ld);
        MTX.hat.ori_asmbl.ld((i_hat*length(MTX.hat.ori.ld)-length(MTX.hat.ori.ld)+1):i_hat*length(MTX.hat.ori.ld), :)...
            = MTX.hat.ori_asmbl.ld((i_hat*length(MTX.hat.ori.ld)-length(MTX.hat.ori.ld)+1):i_hat*length(MTX.hat.ori.ld), :)...
            +MTX.hat.inv.ld;
        
        MTX_K.fre.OR.iter.hat.rd =  MTX_K.fre.OR.I11_I20_IS0*pm.pre.rd(i_hat, 3)+...
            MTX_K.fre.OR.I10_I21_IS0*pm.pre.rd(i_hat, 4)+...
            MTX_K.fre.OR.I10_I20_IS1*0.01;
        MTX.hat.ori.rd = MTX_K.fre.OR.iter.hat.rd+a1*MTX_C.fre.OR.trial.loop+a2*MTX_M.fre.OR.all;
        MTX.hat.inv.rd = inv(MTX.hat.ori.rd);
        MTX.hat.ori_asmbl.rd((i_hat*length(MTX.hat.ori.rd)-length(MTX.hat.ori.rd)+1):i_hat*length(MTX.hat.ori.rd), :)...
            = MTX.hat.ori_asmbl.rd((i_hat*length(MTX.hat.ori.rd)-length(MTX.hat.ori.rd)+1):i_hat*length(MTX.hat.ori.rd), :)...
            +MTX.hat.inv.rd;
    end
end

MTX.hat.ori_asmbl.lu = zeros(pm.num*length(MTX_M.fre.OR.all), length(MTX_M.fre.OR.all));
MTX.hat.ori_asmbl.ru = zeros(pm.num*length(MTX_M.fre.OR.all), length(MTX_M.fre.OR.all));
MTX.hat.ori_asmbl.ld = zeros(pm.num*length(MTX_M.fre.OR.all), length(MTX_M.fre.OR.all));
MTX.hat.ori_asmbl.rd = zeros(pm.num*length(MTX_M.fre.OR.all), length(MTX_M.fre.OR.all));