function out = Rec139(Rec)
%
% ABAQUS concentrated electrical nodal current output to MATLAB
% 
% Syntax
%     #Rec# = Fil2str('*.fil');
%     #out# = Rec139(#Rec#)
%
% Description
%     Read concentrated electrical nodal current output from the results
%     (*.fil) file generated from the ABAQUS finite element software. The
%     asterisk (*) is replaced by the name of the results file. The record
%     key for concentrated electrical nodal current output is 139. See
%     section < < Results file output format > > in ABAQUS Analysis User's manual
%     for more details.
%     The following options with parameters have to be specified in the
%     ABAQUS input file for the results (*.fil) file to be created and to
%     contain concentrated electrical nodal current results:
%         ...
%         *FILE FORMAT, ASCII
%         *NODE FILE
%         CECUR
%         ...
%     NOTE: The results file (*.fil) must be placed in the same directory
%     with the MATLAB source files in order to be processed.
%     
% Input parameters
%     #Rec# (string) is an one-row string containing the ASCII code of the
%         ABAQUS results (*.fil) file. It is generated by the function
%         Fil2str.m.
% 
% Output parameters
%     #out# ([#n# x 2]) is a double array containing the attributes of
%         the record key 139 as follows:
%         Column  1  –  Node number. 
%         Column  2  –  Electrical current. 
%         where #n# is the number of nodes multiplied by the number of
%         increments. If the results file does not contain the desired
%         output, #out# will be an empty array
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2016 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing (submitted)
%
%

ind = strfind(Rec,'I 3139I'); % record key for node concentrated electrical nodal current output (139)
if isempty(ind)
    out=[];
    return;
end
nextpos=numel('I 3139')+1;
for i=1:numel(ind)
    % check the record
    Rec2=Rec(ind(i)-7:ind(i));
    indNW=strfind(Rec2,'*'); % record starting position
    % ensure that the record exists and that the record type key is at
    % location 2
    if isempty(indNW) || indNW>3
        ind(i)=NaN;
        continue;
    end
end
ind(isnan(ind))=[];
% Initialize
NodeNum=zeros(numel(ind),1);
NodeOut=zeros(numel(ind),1);
for i=1:numel(ind)
    % number of digits of node number
    ind1=ind(i)+nextpos; % 1st digit of 2-digit integer of 3rd data item
    ind2=ind(i)+nextpos+1; % 2nd digit of 2-digit integer of 3rd data item
    a1=str2num(Rec(ind1:ind2));
    % Node number
    ind1=ind1+2; % +2 digits
    ind2=ind2+a1; % +2-digit integer
    NodeNum(i)=str2num(Rec(ind1:ind2));
    % concentrated electrical nodal current
    ind1=ind2+1+1; % +1 character+1
    ind2=ind2+1+22; % +1 character +22 floating point digits
    NodeOut(i)=str2num(Rec(ind1:ind2));
end
% Assemply of matrices for output
out=[NodeNum NodeOut];

end

