function out = Rec1940(Rec)
%
% ABAQUS label cross-reference output to MATLAB
% 
% Syntax
%     #Rec# = Fil2str('*.fil');
%     #out# = Rec1940(#Rec#)
%
% Description
%     Read label cross-reference output from the results (*.fil) file
%     generated from the ABAQUS finite element software. The asterisk (*)
%     is replaced by the name of the results file. The record key for label
%     cross-reference output is 1940. See section < < Results file output
%     format > > in ABAQUS Analysis User's manual for more details.
%     The following option with parameter has to be specified in the ABAQUS
%     input file for the results (*.fil) file to be created:
%         ...
%         *FILE FORMAT, ASCII
%         ...
%     NOTE: The results file (*.fil) must be placed in the same directory
%     with the MATLAB source files in order to be processed.
%     
% Input parameters
%     #Rec# (string) is an one-row string containing the ASCII code of the
%         ABAQUS results (*.fil) file. It is generated by the function
%         Fil2str.m.
% 
% Output parameters
%     #out# ([#n# x 2]) is a cell array containing the attributes of
%         the record key 1940 as follows:
%         Column  1  –  Integer reference.
%         Column  2  –  Label (10A8 format).
%         where #n# is the number of elements.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2016 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing (submitted)
%
%

ind = strfind(Rec,'I 41940'); % record key for label cross-reference output (1940)
if isempty(ind)
    out=[];
    return;
end
nextpos=numel('I 41940')+1;
% Initialize record length matrix
NW=zeros(numel(ind),1);
for i=1:numel(ind)
    % find the record length (NW)
    Rec2=Rec(ind(i)-7:ind(i));
    indNW=strfind(Rec2,'*'); % record starting position
    % ensure that the record exists and that the record type key is at
    % location 2
    if isempty(indNW) || indNW>3
        ind(i)=NaN;
        continue;
    end
    % number of digits of record length
    ind1=indNW+2; % 1st digit of 2-digit integer of 1st data item
    ind2=indNW+2+1; % 2nd digit of 2-digit integer of 1st data item
    a1=str2num(Rec2(ind1:ind2));
    % Record length (NW)
    ind1=ind1+2; % +2 digits
    ind2=ind2+a1; % +2-digit integer
    NW(i)=str2num(Rec2(ind1:ind2));
end
ind=ind(~isnan(ind));
EleNum=zeros(numel(ind),1);
EleType=char(zeros(numel(ind),8*(max(NW)-3)));
for i=1:numel(ind)
    % number of digits of integer reference
    ind1=ind(i)+nextpos; % 1st digit of 2-digit integer of 3rd data item
    ind2=ind(i)+nextpos+1; % 2nd digit of 2-digit integer of 3rd data item
    a1=str2num(Rec(ind1:ind2));
    % Integer reference
    ind1=ind1+2; % +2 digits
    ind2=ind2+a1; % +2-digit integer
    EleNum(i)=str2num(Rec(ind1:ind2));
    % Label
    ind1=ind1+a1+1; % +2-digit integer+1 character
    ind2=ind2+8+1; % +8-character string+1
    EleType(i,1:8)=Rec(ind1:ind2);
    for j=1:NW(i)-4
        % label
        ind1=ind2+1+1; % +1 character+1
        ind2=ind2+8+1; % +8-character string+1
        EleType(i,1+8*j:8+8*j)=Rec(ind1:ind2);
    end
end
% Assemply of matrices for output
out=[num2cell(EleNum) cellstr(EleType)];

end

