function out = Rec1911(Rec)
%
% ABAQUS output request definition output to MATLAB
% 
% Syntax
%     #Rec# = Fil2str('*.fil');
%     #out# = Rec1911(#Rec#)
%
% Description
%     Read output request definition from the results (*.fil) file
%     generated from the ABAQUS finite element software. The asterisk (*)
%     is replaced by the name of the results file. The record key for
%     output request definition is 1911. See section < < Results file output
%     format > > in ABAQUS Analysis User's manual for more details.
%     The following option with parameter has to be specified in the ABAQUS
%     input file for the results (*.fil) file to be created:
%         ...
%         *FILE FORMAT, ASCII
%         ...
%     NOTE: The results file (*.fil) must be placed in the same directory
%     with the MATLAB source files in order to be processed.
%     
% Input parameters
%     #Rec# (string) is an one-row string containing the ASCII code of the
%         ABAQUS results (*.fil) file. It is generated by the function
%         Fil2str.m.
% 
% Output parameters
%     #out# ([#n# x 3]) is a cell array containing the attributes of
%         the record key 1911 as follows:
%         Column  1  -  Flag for element-based output (0), nodal output
%         (1), modal output (2), or element set energy output (3).
%         Column  2  -  Set name (node or element set) used in the request
%         (A8 format). This attribute is blank if no set was specified.
%         Column  3  -  Element type (only for element output, A8 format). 
%         where #n# is the number of output request definitions.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2016 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing (submitted)
%
%

ind = strfind(Rec,'I 41911'); % record key for output request definition output (1911)
if isempty(ind)
    out=[];
    return;
end
nextpos=numel('I 41911')+1;
% Initialize record length matrix
NW=zeros(numel(ind),1);
for i=1:numel(ind)
    % find the record length (NW)
    Rec2=Rec(ind(i)-7:ind(i));
    indNW=strfind(Rec2,'*'); % record starts with *
    % ensure that the record exists and that the record type key is at location 2
    if isempty(indNW) || indNW>3
        ind(i)=NaN;
        continue;
    end
    % number of digits of record length
    ind1=indNW+2; % 1st digit of 2-digit integer of 1st data item
    ind2=indNW+2+1; % 2nd digit of 2-digit integer of 1st data item
    a1=str2num(Rec2(ind1:ind2));
    % Record length (NW)
    ind1=ind1+2; % +2 digits
    ind2=ind2+a1; % +2-digit integer
    NW(i)=str2num(Rec2(ind1:ind2));
end
ind=ind(~isnan(ind));
OutFlag=zeros(numel(ind),1);
SetName=char(zeros(numel(ind),8));
EleType=char(zeros(numel(ind),8));
for i=1:numel(ind)
    % number of digits of output flag
    ind1=ind(i)+nextpos; % 1st digit of 2-digit integer of 3rd data item
    ind2=ind(i)+nextpos+1; % 2nd digit of 2-digit integer of 3rd data item
    a1=str2num(Rec(ind1:ind2));
    % Output flag
    ind1=ind1+2; % +2 digits
    ind2=ind2+a1; % +2-digit integer
    OutFlag(i)=str2num(Rec(ind1:ind2));
    % Set name
    ind1=ind1+a1+1; % +2-digit integer+1
    ind2=ind2+8+1; % +8-character string+1
    SetName(i,:)=Rec(ind1:ind2);
    % Check if element type is not defined
    if strcmp(Rec(ind1+8),'*')
        continue
    end
    % Element type
    ind1=ind1+8+1; % +8-character string+1
    ind2=ind2+8+1; % +8-character string+1
    EleType(i,:)=Rec(ind1:ind2);
end
% Assemply of matrices for output
out=[num2cell(OutFlag) cellstr(SetName) cellstr(EleType)];

end

