function out = Rec1902(Rec)
%
% ABAQUS active degrees of freedom output to MATLAB
%
% Syntax
%     #Rec# = Fil2str('*.fil');
%     #out# = Rec1902(#Rec#)
%
% Description
%     Read active degrees of freedom output from the results (*.fil) file
%     generated from the ABAQUS finite element software. The asterisk (*)
%     is replaced by the name of the results file. The record key for
%     active degrees of freedom output is 1902. See section < < Results file
%     output format > > in ABAQUS Analysis User's manual for more details. The
%     following option with parameter has to be specified in the ABAQUS
%     input file for the results (*.fil) file to be created:
%         ...
%         *FILE FORMAT, ASCII
%         ...
%     NOTE: The results file (*.fil) must be placed in the same directory
%     with the MATLAB source files in order to be processed.
%
% Input parameters
%     #Rec# (string) is an one-row string containing the ASCII code of the
%         ABAQUS results (*.fil) file. It is generated by the function
%         Fil2str.m.
%
% Output parameters
%     #out# ([1 x 30]) is an array containing the attributes of the record
%         key 1902 as follows:
%         Column  1  -  Location in nodal arrays of degree of freedom 1 (0
%         if DOF 1 is not active in the model).
%         Column  2  -  Location in nodal arrays of degree of freedom 2 (0
%         if DOF 2 is not active in the model).
%         Column  3  -  etc.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2016 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing (submitted)
%
%

ind = strfind(Rec,'I 41902'); % record key for active degrees of freedom output (1902)
% give empty array if not active degrees of freedom output is specified
if isempty(ind)
    out=[];
    return;
end
nextpos=numel('I 41902')+1;
% Initialize record length matrix
NW=zeros(numel(ind),1);
for i=1:numel(ind)
    % find the record length (NW)
    Rec2=Rec(ind(i)-7:ind(i));
    indNW=strfind(Rec2,'*'); % record starting position
    % ensure that the record exists and that the record type key is at location 2
    if isempty(indNW) || indNW>3
        ind(i)=NaN;
        continue;
    end
    % number of digits of record length
    ind1=indNW+2; % 1st digit of 2-digit integer of 1st data item
    ind2=indNW+2+1; % 2nd digit of 2-digit integer of 1st data item
    a1=str2num(Rec2(ind1:ind2));
    % Record length (NW)
    ind1=ind1+2; % +2 digits
    ind2=ind2+a1; % +2-digit integer
    NW(i)=str2num(Rec2(ind1:ind2));
end
ind=ind(~isnan(ind));
ActDofs=zeros(numel(ind),max(NW)-2);
for i=1:numel(ind)
    ind2=ind(i)+nextpos-2;
    % Dof numbers
    for j=2:NW(i)-2
        % number of digits of dof number
        ind1=ind2+1+1; % +1 character+1
        ind2=ind2+2+1; % +2 digits+1
        a2=str2num(Rec(ind1:ind2));
        % dof number
        ind1=ind1+2; % +2 digits
        ind2=ind2+a2; % +2-digit integer
        ActDofs(i,j)=str2num(Rec(ind1:ind2));
    end
end
% Assemply of matrices for output
out=ActDofs;

end

